### ISSUE TITLE
Incorrect unit specification in DUSRSECJ.jcl

### ISSUE THREAD

**Issue by russell-bonner** [aws-samples/aws-mainframe-modernization-carddemo#2]
In  DUSRSECJ.jcl / STEP01, for the SYSUT2 allocation, the UNIT paramater specifies UNIT=SYSAD. This should be UNIT=SYSDA. 

Using latest version of code on the 'main branch'. Can confirm the amendment allocates successfully on z/OS.

**Comment by snjarao** [comment]
Thanks Russell,  

We have addressed it

Sanjay

**Comment by snjarao** [comment]
Corrected SYSAD to SYSDA as advised
