### ISSUE TITLE
Missing jobs?

### ISSUE THREAD

**Issue by PepitoFS** [aws-samples/aws-mainframe-modernization-carddemo#5]
Could you please explain where we can find two referenced jobs and COBOL apps:

Job	Program	Function
CBTRNLDJ	CBTRNLDC	Load Transactions
CBTRNRPJ	CBTRNRPC	Reports

**Comment by snjarao** [comment]
Pepito,

The 2 jobs named in the list are not required in this release of card demo.

We are updating the list of JCLs in the documentation to reflect the current inventory

**Comment by snjarao** [comment]
Revision to README file done and merged into main
