### ISSUE TITLE
Missing UTIL folder with sample JCLs to compile the programs

### ISSUE THREAD

**Issue by plavjanik** [aws-samples/aws-mainframe-modernization-carddemo#7]
Step #4 (Compile the Programs) refers to UTIL folders:

> We have however provided some sample JCLs in UTIL folders in git to help you craft the JCL

However, there is no UTIL folder and I do not see a JCL that invokes a COBOL compiler.

Can you provide sample JCLs for building the CARDDEMO?

**Comment by snjarao** [comment]
Thanks for pointing this out. 

We have provided sample compile JCLs in the samples folder and have updated the README

Note that these JCLs are only samples. You will still need to speak to your administrator and follow the compile JCL process that is approved in your environment

**Comment by plavjanik** [comment]
Thank you. I am installing it to my own ZD&T now so I can do everything :-) I am thinking about automating the build and deployment process using Zowe CLI (https://www.zowe.org/). Would you be interested if I contribute such scripts?

**Comment by snjarao** [comment]
Yes indeed.

Sent from my iPhone. Please excuse abbreviations and typos

On Oct 13, 2022, at 2:41 AM, Petr Plavjaník ***@***.***> wrote:

﻿

Thank you. I am installing it to my own ZD&T now so I can do everything :-) I am thinking about automating the build and deployment process using Zowe CLI (https://www.zowe.org/). Would you be interested if I contribute such scripts?
