### ISSUE TITLE
Invalid data in supplied ASCII files 

### ISSUE THREAD

**Issue by russell-bonner** [aws-samples/aws-mainframe-modernization-carddemo#9]
In the data files in /app/data/ASCII, there are several files that contain account data in S9(10)V99 format. An example would be acctdata.txt. On the mainframe, in EBCDIC, the last byte of this field is x'C0' presenting the sign and the last data half-byte. This is correct, and x'C0' is represented by the character value '{' - opening brace. 

However, it looks like this data has been transferred without change to ASCII format, with standard EBCDIC -> ASCII conversion to create the data files in /app/data/ASCII. In these files, since they are ASCII, the '{' character now represents x'7B' changing the context of the data. As an example, in the Micro Focus Enterprise Developer CICS environment in ASCII, the account lookup still works, but all account data is now negative, meaning no bill payments (option 10) can be made. 

The solution is to globally change all '{' characters in acctdata.txt to 'À' (A with French grave accent). This  represents x'C0' in US ASCII and the hex data is as expected. 

This has been tested successfully with the ACCTDAT VSAM file (created from acctdata.txt) in an Micro Focus Enterprise Developer environment with the ASCII codeset set. 

I note that the same '{' characters are also present in in the dispgrp.txt and tcatbal.txt files in the /app/data/ASCII folder, but these have not been changed or tested,

**Comment by snjarao** [comment]
Looking into this

**Comment by arunkse** [comment]
Hi Russell, 

Thank you for providing the feedback. 

The ASCII data was created mainly to setup initial data for CardDemo application on the Mainframe itself. We recommend you to use the EBCDIC data and take it through the migration process for the target environment. 

You could still use the ASCII data with EBCDIC sign character for Zoned Decimal fields in the Micro Focus target environment if the programs are compiled with compiler directive SIGN”EBCDIC”.

**Comment by russell-bonner** [comment]
Hi Arun, thanks for your response. It makes sense, and is a misunderstanding on my part on the purpose of the supplied ASCII files which I thought were for local (off-platform) usage. I'll close this issue.
